M48
; DRILL file KiCad 10.0.0 date 2026-04-14T13:01:36
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-04-14T13:01:36-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0079
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.0118
%
G90
G05
T1
X4.1929Y-4.6654
X4.2323Y-4.6654
T2
X4.1929Y-4.5
M30
